### ISSUE TITLE
Deye SUN600 can not be added

### ISSUE THREAD

**Issue by SirBen88** [davidrapan/ha-solarman#287]
### Description

Try to add my Deye SUN600 micro inverter, but it shows an error (I replaced the Inverter ID by xxx): 
[XXXXXXXXXX] Device autodetection failed. [UpdateFailed: [XXXXXXXXXX] ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()]

I can access the inverter via IP adress and I used the Device serial number and not the Inverter serial number.
The port is set to 8899, yaml set to auto or micro (doesn't matter), MPPTs set to 2 and Phases set to 1.

### Reproduction Steps

Go back to v24.10.12 and it is working. Go to v24.10.16 or later -> not working.
Always trying to delete existing device and add a new one.
HAOS version is: 2024.12.0

### Log

`[XXXXXXXXXX] Device autodetection failed. [UpdateFailed: [XXXXXXXXXX] ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()]`

### Version

v24.12.04

**Comment by davidrapan** [comment]
Hi @SirBen88, thank you for your report! Please can you try latest version and see if it solves the problem?

😉

**Comment by SirBen88** [comment]
Hey,
I updated to v24.12.06_4 but that does not fix the problem. Still the same failure message as before.
I try to check and uncheck the "mod" checkbox, in "auto" mode and "deye_micro.yaml".

**Comment by davidrapan** [comment]
Could you try to add device w/ debug log enabled, and attach the log here?

**Comment by SirBen88** [comment]
Here the debug log:
```
2024-12-10 10:29:35.965 DEBUG (MainThread) [custom_components.solarman] async_setup_entry({'created_at': '2024-12-10T09:29:00.068933+00:00', 'data': {'name': 'Inverter', 'serial': OBFUSCATED_SERIAL}, 'discovery_keys': {}, 'disabled_by': None, 'domain': 'solarman', 'entry_id': '01JEQYD0X4WC6MG2KGNK1SG4YK', 'minor_version': 4, 'modified_at': '2024-12-10T09:29:00.068939+00:00', 'options': {'host': '192.168.0.60', 'additional_options': {'mppt': 2, 'phase': 1}}, 'pref_disable_new_entities': False, 'pref_disable_polling': False, 'source': 'user', 'title': 'Inverter', 'unique_id': 'solarman_OBFUSCATED_SERIAL', 'version': 1})
2024-12-10 10:29:35.965 DEBUG (MainThread) [custom_components.solarman] async_setup: coordinator.async_config_entry_first_refresh
2024-12-10 10:29:35.965 DEBUG (MainThread) [custom_components.solarman.discovery] discover
2024-12-10 10:29:35.965 DEBUG (MainThread) [custom_components.solarman.discovery] _discover_all: Broadcasting on 192.168.0.60
2024-12-10 10:29:35.965 DEBUG (MainThread) [custom_components.solarman.discovery] _discover
2024-12-10 10:29:35.972 DEBUG (MainThread) [custom_components.solarman.discovery] _discover: [192.168.0.60, E8FDF85F10C0, OBFUSCATED_SERIAL]
2024-12-10 10:29:35.973 DEBUG (MainThread) [custom_components.solarman.provider] Device autodetection is enabled
2024-12-10 10:29:35.973 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Scheduling 1 query request. #-1
2024-12-10 10:29:35.973 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Querying 03 ~ 0000 - 0022 | 0x0000 - 0x0016 # 023 ...
2024-12-10 10:29:35.973 INFO (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Connecting to 192.168.0.60:8899
2024-12-10 10:29:35.982 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] SENT: a5 17 00 10 45 bb 00 b1 f1 71 f7 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 03 00 00 00 17 05 c4 17 15
2024-12-10 10:29:36.086 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: 41 54 2b 59 5a 43 4d 50 56 45 52 3d 4d 57 33 5f 31 36 55 5f 35 34 30 36 5f 32 2e 33 32 2d 44 31 0d 0a 0d 0a
2024-12-10 10:29:36.291 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] RECD: a5 41 00 10 15 bb 73 b1 f1 71 f7 02 01 1f 08 dd 01 b8 14 00 00 00 00 00 00 01 03 2e 00 04 01 00 02 01 32 32 30 39 30 36 37 31 31 32 00 01 00 00 12 0c 07 00 00 00 01 14 12 12 00 00 17 70 00 00 02 01 00 4b 00 00 00 3c 30 00 14 3d 9b 15
2024-12-10 10:29:36.292 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Querying 03 ~ 0000 - 0022 | 0x0000 - 0x0016 # 023 failed, attempts left: 4 [ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()]
2024-12-10 10:29:36.482 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 26 00 04 01 00 02 01 32 32 30 39 30 36 37 31 31 32 00 01 00 00 12 0c 07 00 00 00 01 14 12 12 00 00 17 70 00 00 02 01 7c af
2024-12-10 10:29:36.493 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Fetching failed. [Previous State: Disconnected (-1)]
2024-12-10 10:29:36.493 INFO (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Disconnecting from 192.168.0.60:8899
2024-12-10 10:29:36.493 ERROR (MainThread) [custom_components.solarman.coordinator] Unexpected error fetching Inverter data
Traceback (most recent call last):
  File "/config/custom_components/solarman/api.py", line 242, in get
    responses[(code, start)] = await self.try_read_write(code, start, quantity, f"Querying {code:02X} ~ {start:04} - {end:04} | 0x{start:04X} - 0x{end:04X} # {quantity:03}", True)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/api.py", line 202, in try_read_write
    while attempts_left > 0 and not response:
                                    ^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/solarman/api.py", line 140, in load
    self.device_info = await self.profile.resolve(self.get)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/provider.py", line 116, in resolve
    f = lookup_profile(await request(-1, [set_request(*AUTODETECTION_REQUEST_DEYE)]), self.attributes) if self.auto and request else self.filename
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/api.py", line 256, in get
    raise Exception(f"[{self.config.serial}] {format_exception(e)}") from e
Exception: [OBFUSCATED_SERIAL] ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in __wrap_async_setup
    await self._async_setup()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 351, in _async_setup
    return await self.setup_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/api.py", line 143, in load
    raise Exception(f"[{self.config.serial}] Device setup failed. [{format_exception(e)}]") from e
Exception: [OBFUSCATED_SERIAL] Device setup failed. [Exception: [OBFUSCATED_SERIAL] ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()]
2024-12-10 10:29:36.496 DEBUG (MainThread) [custom_components.solarman.coordinator] async_shutdown
2024-12-10 10:29:36.496 INFO (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Disconnecting from 192.168.0.60:8899
2024-12-10 10:29:40.704 DEBUG (MainThread) [custom_components.solarman.config_flow] ConfigFlowHandler.async_step_user: None
2024-12-10 10:29:40.704 DEBUG (MainThread) [custom_components.solarman.discovery] discover
2024-12-10 10:29:40.704 DEBUG (MainThread) [custom_components.solarman.discovery] _discover_all
2024-12-10 10:29:40.705 DEBUG (MainThread) [custom_components.solarman.discovery] _discover_all: Broadcasting on [IPv4Network('192.168.0.0/24'), IPv4Network('172.30.232.0/23'), IPv4Network('172.30.32.0/23')]
2024-12-10 10:29:40.705 DEBUG (MainThread) [custom_components.solarman.discovery] _discover
2024-12-10 10:29:40.746 DEBUG (MainThread) [custom_components.solarman.discovery] _discover: [192.168.0.60, E8FDF85F10C0, OBFUSCATED_SERIAL]
2024-12-10 10:29:41.770 DEBUG (MainThread) [custom_components.solarman.config_flow] step_user_data_schema: custom_components/solarman/inverter_definitions/: ['Auto', 'afore_2mppt.yaml', 'afore_BNTxxxKTL-2mppt.yaml', 'afore_hybrid.yaml', 'chint_cps-scetl.yaml', 'deye_hybrid.yaml', 'deye_micro.yaml', 'deye_p3.yaml', 'deye_string.yaml', 'invt_xd-tl.yaml', 'kstar_hybrid.yaml', 'megarevo_r-3h.yaml', 'pylontech_Force-H+.yaml', 'pylontech_Force-H.yaml', 'renon_ifl.yaml', 'sofar_g3hyd.yaml', 'sofar_hyd-es.yaml', 'sofar_lsw3.yaml', 'sofar_tlx-g3.yaml', 'sofar_wifikit.yaml', 'solarman_dtsd422-d3.yaml', 'solis_1p-5g.yaml', 'solis_3p-4g+.yaml', 'solis_3p-4g.yaml', 'solis_3p-5g.yaml', 'solis_hybrid.yaml', 'solis_s6-gr1p.yaml', 'swatten_sih-th.yaml', 'tsun_tsol-ms.yaml', 'zcs_azzurro-1ph-tl-v3.yaml', 'zcs_azzurro-hyd-zss-hp.yaml', 'zcs_azzurro-ktl-v3.yaml']
2024-12-10 10:29:41.770 DEBUG (MainThread) [custom_components.solarman.config_flow] step_user_data_schema: data_schema: {'name': <class 'str'>, 'serial': All(Coerce(int, msg=None), Range(min=0, max=4294967295, min_included=True, max_included=True, msg=None), msg=None), 'host': <class 'str'>, 'port': All(Coerce(int, msg=None), Range(min=1, max=65535, min_included=True, max_included=True, msg=None), msg=None), 'lookup_file': In(['Auto', 'afore_2mppt.yaml', 'afore_BNTxxxKTL-2mppt.yaml', 'afore_hybrid.yaml', 'chint_cps-scetl.yaml', 'deye_hybrid.yaml', 'deye_micro.yaml', 'deye_p3.yaml', 'deye_string.yaml', 'invt_xd-tl.yaml', 'kstar_hybrid.yaml', 'megarevo_r-3h.yaml', 'pylontech_Force-H+.yaml', 'pylontech_Force-H.yaml', 'renon_ifl.yaml', 'sofar_g3hyd.yaml', 'sofar_hyd-es.yaml', 'sofar_lsw3.yaml', 'sofar_tlx-g3.yaml', 'sofar_wifikit.yaml', 'solarman_dtsd422-d3.yaml', 'solis_1p-5g.yaml', 'solis_3p-4g+.yaml', 'solis_3p-4g.yaml', 'solis_3p-5g.yaml', 'solis_hybrid.yaml', 'solis_s6-gr1p.yaml', 'swatten_sih-th.yaml', 'tsun_tsol-ms.yaml', 'zcs_azzurro-1ph-tl-v3.yaml', 'zcs_azzurro-hyd-zss-hp.yaml', 'zcs_azzurro-ktl-v3.yaml']), 'additional_options': <homeassistant.data_entry_flow.section object at 0x7f6aad57f0>}
2024-12-10 10:30:10.093 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.openuv_aktueller_uv_index is taking over 10 seconds
2024-12-10 10:30:14.668 DEBUG (MainThread) [custom_components.solarman.config_flow] ConfigFlowHandler.async_step_user: {'name': 'Inverter 2', 'serial': OBFUSCATED_SERIAL, 'host': '192.168.0.60', 'port': 8899, 'lookup_file': 'Auto', 'additional_options': {'mod': False, 'mppt': 2, 'phase': 1, 'battery_nominal_voltage': 48, 'battery_life_cycle_rating': 6000, 'mb_slave_id': 1}}
2024-12-10 10:30:14.669 DEBUG (MainThread) [custom_components.solarman.config_flow] validate_connection: {'name': 'Inverter 2', 'serial': OBFUSCATED_SERIAL, 'host': '192.168.0.60', 'port': 8899, 'lookup_file': 'Auto', 'additional_options': {'mod': False, 'mppt': 2, 'phase': 1, 'battery_nominal_voltage': 48, 'battery_life_cycle_rating': 6000, 'mb_slave_id': 1}}
2024-12-10 10:30:14.669 DEBUG (MainThread) [custom_components.solarman.config_flow] validate_connection: validation passed: {'name': 'Inverter 2', 'serial': OBFUSCATED_SERIAL, 'host': '192.168.0.60', 'port': 8899, 'lookup_file': 'Auto', 'additional_options': {'mod': False, 'mppt': 2, 'phase': 1, 'battery_nominal_voltage': 48, 'battery_life_cycle_rating': 6000, 'mb_slave_id': 1}}
2024-12-10 10:30:19.454 DEBUG (MainThread) [custom_components.solarman] async_setup_entry({'created_at': '2024-12-10T09:29:00.068933+00:00', 'data': {'name': 'Inverter', 'serial': OBFUSCATED_SERIAL}, 'discovery_keys': {}, 'disabled_by': None, 'domain': 'solarman', 'entry_id': '01JEQYD0X4WC6MG2KGNK1SG4YK', 'minor_version': 4, 'modified_at': '2024-12-10T09:29:00.068939+00:00', 'options': {'host': '192.168.0.60', 'additional_options': {'mppt': 2, 'phase': 1}}, 'pref_disable_new_entities': False, 'pref_disable_polling': False, 'source': 'user', 'title': 'Inverter', 'unique_id': 'solarman_OBFUSCATED_SERIAL', 'version': 1})
2024-12-10 10:30:19.455 DEBUG (MainThread) [custom_components.solarman] async_setup: coordinator.async_config_entry_first_refresh
2024-12-10 10:30:19.455 DEBUG (MainThread) [custom_components.solarman.discovery] discover
2024-12-10 10:30:19.455 DEBUG (MainThread) [custom_components.solarman.discovery] _discover_all: Broadcasting on 192.168.0.60
2024-12-10 10:30:19.455 DEBUG (MainThread) [custom_components.solarman.discovery] _discover
2024-12-10 10:30:19.464 DEBUG (MainThread) [custom_components.solarman.discovery] _discover: [192.168.0.60, E8FDF85F10C0, OBFUSCATED_SERIAL]
2024-12-10 10:30:19.465 DEBUG (MainThread) [custom_components.solarman.provider] Device autodetection is enabled
2024-12-10 10:30:19.465 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Scheduling 1 query request. #-1
2024-12-10 10:30:19.465 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Querying 03 ~ 0000 - 0022 | 0x0000 - 0x0016 # 023 ...
2024-12-10 10:30:19.465 INFO (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Connecting to 192.168.0.60:8899
2024-12-10 10:30:19.474 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] SENT: a5 17 00 10 45 c0 00 b1 f1 71 f7 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 03 00 00 00 17 05 c4 1c 15
2024-12-10 10:30:19.579 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: 41 54 2b 59 5a 43 4d 50 56 45 52 3d 4d 57 33 5f 31 36 55 5f 35 34 30 36 5f 32 2e 33 32 2d 44 31 0d 0a 0d 0a
2024-12-10 10:30:19.683 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 26 00 04 01 00 02 01 32 32 30 39 30 36 37 31 31 32 00 01 00 00 12 0c 07 00 00 00 01 14 12 12 00 00 17 70 00 00 02 01 7c af
2024-12-10 10:30:20.279 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:20.881 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:21.480 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 06 cc d6 87 12 00 01 bb 2d
2024-12-10 10:30:22.083 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 10 00 c8 00 14 58 23
2024-12-10 10:30:23.281 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 26 00 04 01 00 02 01 32 32 30 39 30 36 37 31 31 32 00 01 00 00 12 0c 07 00 00 00 01 14 12 12 00 00 17 70 00 00 02 01 7c af
2024-12-10 10:30:23.881 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:24.480 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:25.081 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 06 cc d6 87 12 00 01 bb 2d
2024-12-10 10:30:25.684 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 10 03 e8 00 14 59 ad
2024-12-10 10:30:26.880 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 26 00 04 01 00 02 01 32 32 30 39 30 36 37 31 31 32 00 01 00 00 12 0c 07 00 00 00 01 14 12 12 00 00 17 70 00 00 02 01 7c af
2024-12-10 10:30:27.480 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:28.081 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:28.681 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 06 cc d6 87 12 00 01 bb 2d
2024-12-10 10:30:30.482 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 26 00 04 01 00 02 01 32 32 30 39 30 36 37 31 31 32 00 01 00 00 12 0c 07 00 00 00 01 14 12 12 00 00 17 70 00 00 02 01 7c af
2024-12-10 10:30:31.083 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:31.682 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:32.280 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 06 cc d6 87 12 00 01 bb 2d
2024-12-10 10:30:32.884 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 10 00 c8 00 14 58 23
2024-12-10 10:30:34.082 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 26 00 04 01 00 02 01 32 32 30 39 30 36 37 31 31 32 00 01 00 00 12 0c 07 00 00 00 01 14 12 12 00 00 17 70 00 00 02 01 7c af
2024-12-10 10:30:34.683 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:35.281 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:35.885 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 06 cc d6 87 12 00 01 bb 2d
2024-12-10 10:30:36.484 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 10 03 e8 00 14 59 ad
2024-12-10 10:30:37.680 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 26 00 04 01 00 02 01 32 32 30 39 30 36 37 31 31 32 00 01 00 00 12 0c 07 00 00 00 01 14 12 12 00 00 17 70 00 00 02 01 7c af
2024-12-10 10:30:38.283 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:38.476 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Querying 03 ~ 0000 - 0022 | 0x0000 - 0x0016 # 023 failed, attempts left: 4 [TimeoutError]
2024-12-10 10:30:38.676 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] SENT: a5 17 00 10 45 c1 00 b1 f1 71 f7 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 03 00 00 00 17 05 c4 1d 15
2024-12-10 10:30:38.881 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] V5_MISMATCH: aa 03 0a 00 00 00 00 00 00 00 00 00 00 be 9c
2024-12-10 10:30:38.889 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] RECD: a5 41 00 10 15 c1 74 b1 f1 71 f7 02 01 5d 08 dd 01 f6 14 00 00 00 00 00 00 01 03 2e 00 04 01 00 02 01 32 32 30 39 30 36 37 31 31 32 00 01 00 00 12 0c 07 00 00 00 01 14 12 12 00 00 17 70 00 00 02 01 00 4b 00 00 00 3c 30 00 14 3d 1e 15
2024-12-10 10:30:38.889 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Querying 03 ~ 0000 - 0022 | 0x0000 - 0x0016 # 023 failed, attempts left: 3 [ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()]
2024-12-10 10:30:39.291 DEBUG (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Fetching failed. [Previous State: Disconnected (-1)]
2024-12-10 10:30:39.291 INFO (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Disconnecting from 192.168.0.60:8899
2024-12-10 10:30:39.291 ERROR (MainThread) [custom_components.solarman.coordinator] Unexpected error fetching Inverter data
Traceback (most recent call last):
  File "/config/custom_components/solarman/api.py", line 242, in get
    responses[(code, start)] = await self.try_read_write(code, start, quantity, f"Querying {code:02X} ~ {start:04} - {end:04} | 0x{start:04X} - 0x{end:04X} # {quantity:03}", True)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/api.py", line 202, in try_read_write
    while attempts_left > 0 and not response:
                                    ^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/solarman/api.py", line 140, in load
    self.device_info = await self.profile.resolve(self.get)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/provider.py", line 116, in resolve
    f = lookup_profile(await request(-1, [set_request(*AUTODETECTION_REQUEST_DEYE)]), self.attributes) if self.auto and request else self.filename
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/api.py", line 256, in get
    raise Exception(f"[{self.config.serial}] {format_exception(e)}") from e
Exception: [OBFUSCATED_SERIAL] ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in __wrap_async_setup
    await self._async_setup()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 351, in _async_setup
    return await self.setup_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/api.py", line 143, in load
    raise Exception(f"[{self.config.serial}] Device setup failed. [{format_exception(e)}]") from e
Exception: [OBFUSCATED_SERIAL] Device setup failed. [Exception: [OBFUSCATED_SERIAL] ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()]
2024-12-10 10:30:39.294 DEBUG (MainThread) [custom_components.solarman.coordinator] async_shutdown
2024-12-10 10:30:39.295 INFO (MainThread) [custom_components.solarman.api] [OBFUSCATED_SERIAL] Disconnecting from 192.168.0.60:8899

```

**Comment by SirBen88** [comment]
I manually updated to v24.12.08_11 and now it is working again!
THANK YOU!

**Comment by SirBen88** [comment]
v24.12.08_11 fixed the problem.
