### ISSUE TITLE
Invalid config after latest update to v24.12.08_10

### ISSUE THREAD

**Issue by MichaelSmet182** [davidrapan/ha-solarman#309]
### Description

After the latest update has been installed config has become invalid

### Reproduction Steps

Invalid config
The following integrations and platforms could not be set up:

[solarman](https://github.com/davidrapan/ha-solarman) ([Show logs](http://192.168.68.20:8123/config/logs?filter=solarman))
Please check your config and [logs](http://192.168.68.20:8123/config/logs).

### Log

[HA SOLARMAN log.docx](https://github.com/user-attachments/files/18066386/HA.SOLARMAN.log.docx)

### Version

24.12.08

### Home Assistant Version

2024.12.1

**Comment by davidrapan** [comment]
Hi @MichaelSmet182, please provide log w/ `.log` ext.

**Comment by afkdk** [comment]
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 21:45:51 (1 occurrences)
Last logged: 21:45:51

Setup failed for custom integration 'solarman': Unable to import component: No module named 'pysolarmanv5'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/solarman/__init__.py", line 16, in <module>
    from .coordinator import Inverter, InverterCoordinator
  File "/config/custom_components/solarman/coordinator.py", line 11, in <module>
    from .api import Inverter
  File "/config/custom_components/solarman/api.py", line 16, in <module>
    from .include.pysolarmanv5 import PySolarmanV5Async, V5FrameError
  File "/config/custom_components/solarman/include/pysolarmanv5/__init__.py", line 4, in <module>
    from pysolarmanv5.pysolarmanv5 import PySolarmanV5
ModuleNotFoundError: No module named 'pysolarmanv5'

**Comment by davidrapan** [comment]
I's not issue w/ this integration but, either:
* Upgrade HA Core
* Downgrade and then upgrade HA Core
* Update integration to the latest version where is not pysolarmanv5 used as module

**Comment by afkdk** [comment]
Ack'ed - please disregard my aim to help woth the log...

The error message and symptoms are identical!
I have just installed the new core 12.2 release to ser if that Jeps - same error/bug with missing sutoload...

Then it is likely the custom integration that neefs dine update?

**Comment by davidrapan** [comment]
> Then it is likely the custom integration that needs done update?

It certainly does not, this is issue w/ HA but if you install latest version issue will be gone because there isn't dependency on pysolarmav5 anymore.

**Comment by znack14** [comment]
After updating to 12.2, I have the same error.

**Comment by Adminius** [comment]
same here:
Core 12.2, Plugin 24.12.08_9
![image](https://github.com/user-attachments/assets/1a431d97-bac5-4dc6-bd39-d890b5683c6d)
No logs, can't even start debug. All devices are "**not loaded**"

**Comment by neofral** [comment]
I had the same issue. 
Deleted the device, deleted/uninstalled solarman from hacs, restarted HA.
Installed again the integration, restarted HA. after that i reconfigured my device.
All working fine after that

**Comment by davidrapan** [comment]
So it looks like migrations had conflicts w/ old entities huh?

**Comment by afkdk** [comment]
> > Then it is likely the custom integration that needs done update?
> 
> It certainly does not, this is issue w/ HA but if you install latest version issue will be gone because there isn't dependency on pysolarmav5 anymore.
> 
> You can read more 'bout this in #299

THANKS for this link that shows the challenge, history, and complexity (when changing the inner plumbing of Python in HA 🤯)

So nice to have this integration working again - APPRECIATE YOUR TIME AND THE GREAT WORK 👍😃

**Comment by gardiol** [comment]
After today's update of Home Assistant, it seems broken again:

```
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 6:25:19 PM (1 occurrences)
Last logged: 6:25:19 PM

Setup failed for custom integration 'solarman': Unable to import component: No module named 'pysolarmanv5'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/solarman/__init__.py", line 16, in <module>
    from .coordinator import Inverter, InverterCoordinator
  File "/config/custom_components/solarman/coordinator.py", line 11, in <module>
    from .api import Inverter
  File "/config/custom_components/solarman/api.py", line 16, in <module>
    from .include.pysolarmanv5 import PySolarmanV5Async, V5FrameError
  File "/config/custom_components/solarman/include/pysolarmanv5/__init__.py", line 4, in <module>
    from pysolarmanv5.pysolarmanv5 import PySolarmanV5
ModuleNotFoundError: No module named 'pysolarmanv5'
```

**Comment by gardiol** [comment]
i updated to  Core 2024.12.2 and noticed this after a few hours...

**Comment by gardiol** [comment]
I am responding to myself: i have reinstalled the integration manually from HACS control panel and it seems to be working. In case it happens to somebody else.

**Comment by davidrapan** [comment]
Yes, the error shows that you were not running the latest version.

**Comment by davidrapan** [comment]
HACS sometimes do that, not sure why.

Anyway some more clarification:
```
from pysolarmanv5.pysolarmanv5 import PySolarmanV5
```
Still loads module and in the latest is:
```
from ..pysolarmanv5 import PySolarmanV5
```
